In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df = df[['Pclass','Name','Sex','Age','Embarked','Survived']]

In [ ]:
df.shape

(891, 6)

In [ ]:
df.head()

,Pclass,Name,Sex,Age,Embarked,Survived
0,3,"Braund, Mr. Owen Harris",male,22.0,S,0
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,C,1
2,3,"Heikkinen, Miss. Laina",female,26.0,S,1
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,S,1
4,3,"Allen, Mr. William Henry",male,35.0,S,0

In [ ]:
df.info

<bound method DataFrame.info of      Pclass                                               Name     Sex   Age  \
0         3                            Braund, Mr. Owen Harris    male  22.0
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2         3                             Heikkinen, Miss. Laina  female  26.0
3         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4         3                           Allen, Mr. William Henry    male  35.0
..      ...                                                ...     ...   ...
886       2                              Montvila, Rev. Juozas    male  27.0
887       1                       Graham, Miss. Margaret Edith  female  19.0
888       3           Johnston, Miss. Catherine Helen "Carrie"  female   NaN
889       1                              Behr, Mr. Karl Howell    male  26.0
890       3                                Dooley, Mr. Patrick    male  32.0

    Embarked  Survived
0          S         0
1          C         1
2          S         1
3          S         1
4          S         0
..       ...       ...
886        S         0
887        S         1
888        S         0
889        C         1
890        Q         0

[891 rows x 6 columns]>

In [ ]:
df.isnull().sum()

Pclass        0
Name          0
Sex           0
Age         177
Embarked      2
Survived      0
dtype: int64

In [ ]:
df = df.dropna()
df.isnull().sum()

Pclass      0
Name        0
Sex         0
Age         0
Embarked    0
Survived    0
dtype: int64

In [ ]:
df['Name'].unique()

array(['Braund, Mr. Owen Harris',
       'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
       'Heikkinen, Miss. Laina',
       'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
       'Allen, Mr. William Henry', 'McCarthy, Mr. Timothy J',
       'Palsson, Master. Gosta Leonard',
       'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
       'Nasser, Mrs. Nicholas (Adele Achem)',
       'Sandstrom, Miss. Marguerite Rut', 'Bonnell, Miss. Elizabeth',
       'Saundercock, Mr. William Henry', 'Andersson, Mr. Anders Johan',
       'Vestrom, Miss. Hulda Amanda Adolfina',
       'Hewlett, Mrs. (Mary D Kingcome) ', 'Rice, Master. Eugene',
       'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
       'Fynney, Mr. Joseph J', 'Beesley, Mr. Lawrence',
       'McGowan, Miss. Anna "Annie"', 'Sloper, Mr. William Thompson',
       'Palsson, Miss. Torborg Danira',
       'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
       'Fortune, Mr. Charles Alexander', 'Uruchurtu, Don. Manuel E',
       'Wheadon, Mr. Edward H', 'Meyer, Mr. Edgar Joseph',
       'Holverson, Mr. Alexander Oskar', 'Cann, Mr. Ernest Charles',
       'Vander Planke, Miss. Augusta Maria',
       'Nicola-Yarred, Miss. Jamila',
       'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
       'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',
       'Laroche, Miss. Simonne Marie Anne Andree',
       'Devaney, Miss. Margaret Delia',
       'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
       'Panula, Master. Juha Niilo', 'Nosworthy, Mr. Richard Cater',
       'Harper, Mrs. Henry Sleeper (Myna Haxtun)',
       'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',
       'Ostby, Mr. Engelhart Cornelius', 'Rugg, Miss. Emily',
       'Novel, Mr. Mansouer', 'West, Miss. Constance Mirium',
       'Goodwin, Master. William Frederick', 'Sirayanian, Mr. Orsen',
       'Harris, Mr. Henry Birkhardt', 'Skoog, Master. Harald',
       'Nye, Mrs. (Elizabeth Ramell)', 'Crease, Mr. Ernest James',
       'Andersson, Miss. Erna Alexandra', 'Kink, Mr. Vincenz',
       'Jenkin, Mr. Stephen Curnow', 'Goodwin, Miss. Lillian Amy',
       'Hood, Mr. Ambrose Jr', 'Chronopoulos, Mr. Apostolos',
       'Bing, Mr. Lee', 'Moen, Mr. Sigurd Hansen',
       'Caldwell, Master. Alden Gates', 'Dowdell, Miss. Elizabeth',
       'Waelens, Mr. Achille', 'Sheerlinck, Mr. Jan Baptist',
       'Carrau, Mr. Francisco M', 'Ilett, Miss. Bertha',
       'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
       'Ford, Mr. William Neal', 'Fortune, Miss. Mabel Helen',
       'Celotti, Mr. Francesco', 'Christmann, Mr. Emil',
       'Andreasson, Mr. Paul Edvin', 'Chaffee, Mr. Herbert Fuller',
       'Dean, Mr. Bertram Frank', 'Coxon, Mr. Daniel',
       'Goldschmidt, Mr. George B', 'Greenfield, Mr. William Bertram',
       'Doling, Mrs. John T (Ada Julia Bone)', 'Kantor, Mr. Sinai',
       'Petranec, Miss. Matilda', 'White, Mr. Richard Frasar',
       'Johansson, Mr. Gustaf Joel', 'Gustafsson, Mr. Anders Vilhelm',
       'Mionoff, Mr. Stoytcho', 'Salkjelsvik, Miss. Anna Kristine',
       'Rekic, Mr. Tido', 'Porter, Mr. Walter Chamberlain',
       'Zabour, Miss. Hileni', 'Barton, Mr. David John',
       'Jussila, Miss. Katriina', 'Attalah, Miss. Malake',
       'Pekoniemi, Mr. Edvard', 'Connors, Mr. Patrick',
       'Turpin, Mr. William John Robert', 'Baxter, Mr. Quigg Edmond',
       'Andersson, Miss. Ellis Anna Maria', 'Hickman, Mr. Stanley George',
       'Nasser, Mr. Nicholas', 'Webber, Miss. Susan',
       'White, Mr. Percival Wayland', 'Nicola-Yarred, Master. Elias',
       'Madsen, Mr. Fridtjof Arne', 'Ekstrom, Mr. Johan',
       'Drazenoic, Mr. Jozef', 'Coelho, Mr. Domingos Fernandeo',
       'Robins, Mrs. Alexander A (Grace Charity Laury)',
       'Weisz, Mrs. Leopold (Mathilde Francoise Pede)',
       'Sobey, Mr. Samuel James Hayden', 'Richard, Mr. Emile',
       'Newsom, Miss. Helen Monypeny', 'Futrelle, Mr. Jacques Heath',
       'Osen, Mr. Olaf Elon', 'Giglio, Mr. Victor',
       'Nysten, Miss. Anna Sofia',
       'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)',
       'Burke, Mr. Jeremiah', 'Andrew, Mr. Edgardo Samuel',
       'Nicholls, Mr. Joseph Charles',
       'Andersson, Mr. August Edvard ("Wennerstrom")',
       'Ford, Miss. Robina Maggie "Ruby"',
       'Navratil, Mr. Michel ("Louis M Hoffman")',
       'Byles, Rev. Thomas Roussel Davids', 'Bateman, Rev. Robert James',
       'Pears, Mrs. Thomas (Edith Wearne)', 'Meo, Mr. Alfonzo',
       'van Billiard, Mr. Austin Blyler', 'Williams, Mr. Charles Duane',
       'Gilnagh, Miss. Katherine "Katie"', 'Corn, Mr. Harry',
       'Cribb, Mr. John Hatfield',
       'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)',
       'Bengtsson, Mr. John Viktor', 'Calic, Mr. Jovo',
       'Panula, Master. Eino Viljami',
       'Goldsmith, Master. Frank John William "Frankie"',
       'Skoog, Mrs. William (Anna Bernhardina Karlsson)', 'Ling, Mr. Lee',
       'Van der hoef, Mr. Wyckoff', 'Rice, Master. Arthur',
       'Johnson, Miss. Eleanor Ileen', 'Sivola, Mr. Antti Wilhelm',
       'Smith, Mr. James Clinch', 'Klasen, Mr. Klas Albin',
       'Isham, Miss. Ann Elizabeth', 'Hale, Mr. Reginald',
       'Leonard, Mr. Lionel', 'Asplund, Master. Clarence Gustaf Hugo',
       'Becker, Master. Richard F', 'Kink-Heilmann, Miss. Luise Gretchen',
       'Romaine, Mr. Charles Hallace ("Mr C Rolmane")',
       'Bourke, Mr. John', 'Turcin, Mr. Stjepan', 'Pinsky, Mrs. (Rosa)',
       'Carbines, Mr. William',
       'Andersen-Jensen, Miss. Carla Christine Nielsine',
       'Navratil, Master. Michel M',
       'Brown, Mrs. James Joseph (Margaret Tobin)',
       'Lurette, Miss. Elise', 'Olsen, Mr. Karl Siegwart Andreas',
       'Yrois, Miss. Henriette ("Mrs Harbeck")',
       'Vande Walle, Mr. Nestor Cyriel', 'Johanson, Mr. Jakob Alfred',
       'Youseff, Mr. Gerious', 'Cohen, Mr. Gurshon "Gus"',
       'Strom, Miss. Telma Matilda', 'Backstrom, Mr. Karl Alfred',
       'Albimona, Mr. Nassef Cassem', 'Carr, Miss. Helen "Ellen"',
       'Blank, Mr. Henry', 'Ali, Mr. Ahmed', 'Cameron, Miss. Clear Annie',
       'Perkin, Mr. John Henry', 'Givard, Mr. Hans Kristensen',
       'Newell, Miss. Madeleine', 'Honkanen, Miss. Eliina',
       'Jacobsohn, Mr. Sidney Samuel', 'Bazzani, Miss. Albina',
       'Harris, Mr. Walter', 'Sunderland, Mr. Victor Francis',
       'Bracken, Mr. James H', 'Green, Mr. George Henry',
       'Hoyt, Mr. Frederick Maxfield', 'Berglund, Mr. Karl Ivar Sven',
       'Mellors, Mr. William John', 'Lovell, Mr. John Hall ("Henry")',
       'Fahlstrom, Mr. Arne Jonas',
       'Harris, Mrs. Henry Birkhardt (Irene Wallach)',
       'Larsson, Mr. Bengt Edvin', 'Sjostedt, Mr. Ernst Adolf',
       'Asplund, Miss. Lillian Gertrud',
       'Leyson, Mr. Robert William Norman', 'Hold, Mr. Stephen',
       'Collyer, Miss. Marjorie "Lottie"',
       'Pengelly, Mr. Frederick William', 'Hunt, Mr. George Henry',
       'Coleridge, Mr. Reginald Charles', 'Maenpaa, Mr. Matti Alexanteri',
       'Attalah, Mr. Sleiman', 'Minahan, Dr. William Edward',
       'Lindahl, Miss. Agda Thorilda Viktoria',
       'Hamalainen, Mrs. William (Anna)', 'Beckwith, Mr. Richard Leonard',
       'Carter, Rev. Ernest Courtenay',
       'Strom, Mrs. Wilhelm (Elna Matilda Persson)',
       'Stead, Mr. William Thomas', 'Lobb, Mr. William Arthur',
       'Rosblom, Mrs. Viktor (Helena Wilhelmina)',
       'Touma, Mrs. Darwis (Hanne Youssef Razi)', 'Cherry, Miss. Gladys',
       'Ward, Miss. Anna', 'Parrish, Mrs. (Lutie Davis)',
       'Asplund, Master. Edvin Rojj Felix', 'Taussig, Mr. Emil',
       'Harrison, Mr. William', 'Reeves, Mr. David',
       'Panula, Mr. Ernesti Arvid', 'Persson, Mr. Ernst Ulrik',
       'Graham, Mrs. William Thompson (Edith Junkins)',
       'Bissette, Miss. Amelia', 'Tornquist, Mr. William Henry',
       'Mellinger, Mrs. (Elizabeth Anne Maidment)',
       'Natsch, Mr. Charles H', 'Andrews, Miss. Kornelia Theodosia',
       'Lindblom, Miss. Augusta Charlotta', 'Rice, Master. Eric',
       'Abbott, Mrs. Stanton (Rosa Hunt)', 'Duane, Mr. Frank',
       'Olsson, Mr. Nils Johan Goransson', 'de Pelsmaeker, Mr. Alfons',
       'Dorking, Mr. Edward Arthur', 'Stankovic, Mr. Ivan',
       'de Mulder, Mr. Theodore', 'Naidenoff, Mr. Penko',
       'Hosono, Mr. Masabumi', 'Connolly, Miss. Kate',
       'Barber, Miss. Ellen "Nellie"',
       'Bishop, Mrs. Dickinson H (Helen Walton)',
       'Levy, Mr. Rene Jacques', 'Haas, Miss. Aloisia',
       'Mineff, Mr. Ivan', 'Hanna, Mr. Mansour',
       'Allison, Miss. Helen Loraine',
       'Baxter, Mrs. James (Helene DeLaudeniere Chaput)',
       'Johnson, Mr. William Cahoone Jr',
       'Allison, Master. Hudson Trevor',
       'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)',
       'Abelson, Mr. Samuel', 'Francatelli, Miss. Laura Mabel',
       'Hays, Miss. Margaret Bechstein', 'Ryerson, Miss. Emily Borie',
       'Lahtinen, Mrs. William (Anna Sylfven)', 'Hendekovic, Mr. Ignjac',
       'Hart, Mr. Benjamin', 'Nilsson, Miss. Helmina Josefina',
       'Kantor, Mrs. Sinai (Miriam Sternin)', 'Moraweck, Dr. Ernest',
       'Wick, Miss. Mary Natalie',
       'Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)',
       'Dennis, Mr. Samuel', 'Danoff, Mr. Yoto',
       'Slayter, Miss. Hilda Mary',
       'Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)',
       'Young, Miss. Marie Grice', 'Nysveen, Mr. Johan Hansen',
       'Ball, Mrs. (Ada E Hall)',
       'Goldsmith, Mrs. Frank John (Emily Alice Brown)',
       'Hippach, Miss. Jean Gertrude', 'Partner, Mr. Austen',
       'Graham, Mr. George Edward', 'Vander Planke, Mr. Leo Edmondus',
       'Pears, Mr. Thomas Clinton', 'Burns, Miss. Elizabeth Margaret',
       'Dahl, Mr. Karl Edwart', 'Blackwell, Mr. Stephen Weart',
       'Navratil, Master. Edmond Roger', 'Fortune, Miss. Alice Elizabeth',
       'Collander, Mr. Erik Gustaf',
       'Sedgwick, Mr. Charles Frederick Waddington',
       'Fox, Mr. Stanley Hubert', 'Brown, Miss. Amelia "Mildred"',
       'Smith, Miss. Marion Elsie',
       'Coutts, Master. William Loch "William"', 'Dimic, Mr. Jovan',
       'Odahl, Mr. Nils Martin', 'Elias, Mr. Tannous',
       'Arnold-Franchi, Mr. Josef', 'Vanden Steen, Mr. Leo Peter',
       'Bowerman, Miss. Elsie Edith', 'Funk, Miss. Annie Clemmer',
       'Skoog, Mr. Wilhelm', 'del Carlo, Mr. Sebastiano',
       'Barbara, Mrs. (Catherine David)', 'Asim, Mr. Adola',
       'Adahl, Mr. Mauritz Nils Martin',
       'Warren, Mrs. Frank Manley (Anna Sophia Atkinson)',
       'Aubart, Mme. Leontine Pauline', 'Harder, Mr. George Achilles',
       'Wiklund, Mr. Jakob Alfred', 'Beavan, Mr. William Thomas',
       'Ringhini, Mr. Sante', 'Palsson, Miss. Stina Viola',
       'Landergren, Miss. Aurora Adelia', 'Widener, Mr. Harry Elkins',
       'Betros, Mr. Tannous', 'Gustafsson, Mr. Karl Gideon',
       'Bidois, Miss. Rosalie', 'Nakid, Miss. Maria ("Mary")',
       'Tikkanen, Mr. Juho',
       'Holverson, Mrs. Alexander Oskar (Mary Aline Towner)',
       'Davies, Mr. Charles Henry', 'Goodwin, Master. Sidney Leonard',
       'Buss, Miss. Kate', 'Lehmann, Miss. Bertha',
       'Carter, Mr. William Ernest', 'Jansson, Mr. Carl Olof',
       'Gustafsson, Mr. Johan Birger', 'Newell, Miss. Marjorie',
       'Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengtsson)',
       'Johansson, Mr. Erik', 'Olsson, Miss. Elina',
       'McKane, Mr. Peter David', 'Pain, Dr. Alfred',
       'Trout, Mrs. William H (Jessie L)', 'Niskanen, Mr. Juha',
       'Adams, Mr. John', 'Jussila, Miss. Mari Aina',
       'Hakkarainen, Mr. Pekka Pietari', 'Oreskovic, Miss. Marija',
       'Gale, Mr. Shadrach', 'Widegren, Mr. Carl/Charles Peter',
       'Richards, Master. William Rowe',
       'Birkeland, Mr. Hans Martin Monsen', 'Minahan, Miss. Daisy E',
       'Sundman, Mr. Johan Julian',
       'Drew, Mrs. James Vivian (Lulu Thorne Christian)',
       'Silven, Miss. Lyyli Karoliina', 'Matthews, Mr. William John',
       'Van Impe, Miss. Catharina', 'Charters, Mr. David',
       'Zimmerman, Mr. Leo',
       'Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren)',
       'Rosblom, Mr. Viktor Richard',
       'Clarke, Mrs. Charles V (Ada Maria Winfield)',
       'Phillips, Miss. Kate Florence ("Mrs Kate Louise Phillips Marshall")',
       'Pickard, Mr. Berk (Berk Trembisky)',
       'Bjornstrom-Steffansson, Mr. Mauritz Hakan',
       'Louch, Mrs. Charles Alexander (Alice Adelaide Slow)',
       'Kallio, Mr. Nikolai Erland', 'Silvey, Mr. William Baird',
       'Carter, Miss. Lucile Polk',
       'Ford, Miss. Doolina Margaret "Daisy"',
       'Richards, Mrs. Sidney (Emily Hocking)', 'Fortune, Mr. Mark',
       'Kvillner, Mr. Johan Henrik Johannesson',
       'Hart, Mrs. Benjamin (Esther Ada Bloomfield)', 'Hampe, Mr. Leon',
       'Petterson, Mr. Johan Emil', 'Reynaldo, Ms. Encarnacion',
       'Dodge, Master. Washington', 'Mellinger, Miss. Madeleine Violet',
       'Seward, Mr. Frederic Kimber', 'Baclini, Miss. Marie Catherine',
       'Peuchen, Major. Arthur Godfrey', 'West, Mr. Edwy Arthur',
       'Foreman, Mr. Benjamin Laventall', 'Goldenberg, Mr. Samuel L',
       'Jalsevac, Mr. Ivan', 'Millet, Mr. Francis Davis',
       'Toomey, Miss. Ellen', 'Anderson, Mr. Harry',
       'Morley, Mr. William', 'Gee, Mr. Arthur H',
       'Milling, Mr. Jacob Christian', 'Goncalves, Mr. Manuel Estanslas',
       'Smart, Mr. John Montgomery', 'Baclini, Miss. Helene Barbara',
       'Cacic, Mr. Luka', 'West, Mrs. Edwy Arthur (Ada Mary Worth)',
       'Jerwan, Mrs. Amin S (Marie Marthe Thuillard)',
       'Strandberg, Miss. Ida Sofia', 'Renouf, Mr. Peter Henry',
       'Braund, Mr. Lewis Richard', 'Karlsson, Mr. Nils August',
       'Hirvonen, Miss. Hildur E', 'Goodwin, Master. Harold Victor',
       'Rouse, Mr. Richard Henry', 'Turkula, Mrs. (Hedwig)',
       'Bishop, Mr. Dickinson H',
       'Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)',
       'Kent, Mr. Edward Austin', 'Somerton, Mr. Francis William',
       'Coutts, Master. Eden Leslie "Neville"', 'Windelov, Mr. Einar',
       'Molson, Mr. Harry Markland', 'Artagaveytia, Mr. Ramon',
       'Stanley, Mr. Edward Roland', 'Eustis, Miss. Elizabeth Mussey',
       'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)',
       'Svensson, Mr. Olof', 'Calic, Mr. Petar', 'Canavan, Miss. Mary',
       'Laitinen, Miss. Kristina Sofia', 'Maioni, Miss. Roberta',
       'Penasco y Castellana, Mr. Victor de Satode',
       'Quick, Mrs. Frederick Charles (Jane Richards)',
       'Olsen, Mr. Henry Margido', 'Lang, Mr. Fang',
       'Daly, Mr. Eugene Patrick', 'McGough, Mr. James Robert',
       'Rothschild, Mrs. Martin (Elizabeth L. Barrett)',
       'Coleff, Mr. Satio', 'Walker, Mr. William Anderson',
       'Lemore, Mrs. (Amelia Milley)',
       'Angle, Mrs. William A (Florence "Mary" Agnes Hughes)',
       'Pavlovic, Mr. Stefo', 'Perreault, Miss. Anne', 'Vovk, Mr. Janko',
       'Hippach, Mrs. Louis Albert (Ida Sophia Fischer)',
       'Farrell, Mr. James', 'Ridsdale, Miss. Lucy',
       'Salonen, Mr. Johan Werner', 'Hocking, Mr. Richard George',
       'Quick, Miss. Phyllis May', 'Elias, Mr. Joseph Jr',
       'Cacic, Miss. Marija', 'Hart, Miss. Eva Miriam',
       'Butt, Major. Archibald Willingham', 'LeRoy, Miss. Bertha',
       'Frolicher, Miss. Hedwig Margaritha', 'Crosby, Miss. Harriet R',
       'Andersson, Miss. Ingeborg Constanzia',
       'Andersson, Miss. Sigrid Elisabeth', 'Beane, Mr. Edward',
       'Douglas, Mr. Walter Donald', 'Nicholson, Mr. Arthur Ernest',
       'Beane, Mrs. Edward (Ethel Clarke)', 'Goldsmith, Mr. Frank John',
       'Davies, Master. John Morgan Jr', 'Thayer, Mr. John Borland Jr',
       'Sharp, Mr. Percival James R', 'Leeni, Mr. Fahim ("Philip Zenni")',
       'Ohman, Miss. Velin', 'Wright, Mr. George',
       'Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")',
       'Taussig, Mrs. Emil (Tillie Mandelbaum)',
       'de Messemaeker, Mrs. Guillaume Joseph (Emma)',
       'Sivic, Mr. Husein', 'Norman, Mr. Robert Douglas',
       'Davies, Mr. Alfred J', 'Stoytcheff, Mr. Ilia',
       'Palsson, Mrs. Nils (Alma Cornelia Berglund)', 'Jonsson, Mr. Carl',
       'Harris, Mr. George',
       'Appleton, Mrs. Edward Dale (Charlotte Lamson)',
       'Flynn, Mr. John Irwin ("Irving")', 'Rush, Mr. Alfred George John',
       'Patchett, Mr. George', 'Garside, Miss. Ethel',
       'Silvey, Mrs. William Baird (Alice Munger)', 'Jussila, Mr. Eiriik',
       'Christy, Miss. Julie Rachel',
       'Thayer, Mrs. John Borland (Marian Longstreth Morris)',
       'Downton, Mr. William James', 'Ross, Mr. John Hugo',
       'Taussig, Miss. Ruth', 'Jarvis, Mr. John Denzil',
       'Frolicher-Stehli, Mr. Maxmillian', 'Gilinski, Mr. Eliezer',
       'Rintamaki, Mr. Matti',
       'Stephenson, Mrs. Walter Bertram (Martha Eustis)',
       'Elsbury, Mr. William James', 'Chapman, Mr. John Henry',
       'Van Impe, Mr. Jean Baptiste', 'Johnson, Mr. Alfred',
       'Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")',
       'Jacobsohn, Mrs. Sidney Samuel (Amy Frances Christy)',
       'Torber, Mr. Ernst William', 'Homer, Mr. Harry ("Mr E Haven")',
       'Lindell, Mr. Edvard Bengtsson', 'Karaic, Mr. Milan',
       'Daniel, Mr. Robert Williams',
       'Laroche, Mrs. Joseph (Juliette Marie Louise Lafargue)',
       'Shutes, Miss. Elizabeth W',
       'Andersson, Mrs. Anders Johan (Alfrida Konstantia Brogren)',
       'Brocklebank, Mr. William Alfred', 'Herman, Miss. Alice',
       'Danbom, Mr. Ernst Gilbert',
       'Lobb, Mrs. William Arthur (Cordelia K Stanlick)',
       'Becker, Miss. Marion Louise', 'Gavey, Mr. Lawrence',
       'Yasbeck, Mr. Antoni', 'Kimball, Mr. Edwin Nelson Jr',
       'Nakid, Mr. Sahid', 'Hansen, Mr. Henry Damsgaard',
       'Bowen, Mr. David John "Dai"', 'Sutton, Mr. Frederick',
       'Kirkland, Rev. Charles Leonard', 'Longley, Miss. Gretchen Fiske',
       'Bostandyeff, Mr. Guentcho',
       'Barkworth, Mr. Algernon Henry Wilson',
       'Lundahl, Mr. Johan Svensson', 'Stahelin-Maeglin, Dr. Max',
       'Skoog, Miss. Mabel', 'Davis, Miss. Mary',
       'Leinonen, Mr. Antti Gustaf', 'Collyer, Mr. Harvey',
       'Panula, Mrs. Juha (Maria Emilia Ojala)', 'Jensen, Mr. Hans Peder',
       'Sagesser, Mlle. Emma', 'Skoog, Miss. Margit Elizabeth',
       'Baclini, Miss. Eugenie', 'Harper, Mr. Henry Sleeper',
       'Cor, Mr. Liudevit', 'Simonius-Blumer, Col. Oberst Alfons',
       'Stanley, Miss. Amy Zillah Elsie', 'Doling, Miss. Elsie',
       'Kalvik, Mr. Johannes Halvorsen', 'Hegarty, Miss. Hanora "Nora"',
       'Hickman, Mr. Leonard Mark', 'Bourke, Mrs. John (Catherine)',
       'Eitemiller, Mr. George Floyd', 'Newell, Mr. Arthur Webster',
       'Frauenthal, Dr. Henry William', 'Badt, Mr. Mohamed',
       'Colley, Mr. Edward Pomeroy', 'Coleff, Mr. Peju',
       'Lindqvist, Mr. Eino William', 'Hickman, Mr. Lewis',
       'Butler, Mr. Reginald Fenton', 'Cook, Mr. Jacob',
       'Brown, Mrs. Thomas William Solomon (Elizabeth Catherine Ford)',
       'Davidson, Mr. Thornton', 'Mitchell, Mr. Henry Michael',
       'Wilhelms, Mr. Charles', 'Edvardsson, Mr. Gustaf Hjalmar',
       'Sawyer, Mr. Frederick Charles', 'Turja, Miss. Anna Sofia',
       'Goodwin, Mrs. Frederick (Augusta Tyler)',
       'Cardeza, Mr. Thomas Drake Martinez', 'Hassab, Mr. Hammad',
       'Olsvigen, Mr. Thor Anderson', 'Goodwin, Mr. Charles Edward',
       'Brown, Mr. Thomas William Solomon',
       'Laroche, Mr. Joseph Philippe Lemercier',
       'Panula, Mr. Jaako Arnold', 'Dakic, Mr. Branko',
       'Fischer, Mr. Eberhard Thelander',
       'Madill, Miss. Georgette Alexandra', 'Dick, Mr. Albert Adrian',
       'Karun, Miss. Manca', 'Saad, Mr. Khalil', 'Weir, Col. John',
       'Chapman, Mr. Charles Henry', 'Kelly, Mr. James',
       'Thayer, Mr. John Borland',
       'Humblen, Mr. Adolf Mathias Nicolai Olsen',
       'Astor, Mrs. John Jacob (Madeleine Talmadge Force)',
       'Silverthorne, Mr. Spencer Victor', 'Barbara, Miss. Saiide',

In [ ]:
from sklearn.preprocessing import LabelEncoder
le_country = LabelEncoder()

In [ ]:
df['Name'] = le_country.fit_transform(df['Name'])
df['Name'].unique()

<ipython-input-30-7404ac142d3c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Name'] = le_country.fit_transform(df['Name'])

array([103, 179, 317, 247,  15, 440, 509, 368, 473, 582,  94, 584,  28,
       673, 322, 554, 672, 248,  79, 442, 612, 511,  44, 238, 661, 687,
       450, 335, 126, 670, 485,   7, 660, 394, 198,  38, 514, 490, 301,
       228, 506, 574, 491, 684, 270, 599, 304, 604, 492, 174,  25, 385,
       354, 271, 339, 151,  86, 458, 120, 208, 675, 590, 132, 346,  52,
       233, 237, 140, 149,  31, 141, 196, 173, 263, 279, 204, 376, 533,
       689, 361, 283, 456, 580, 547, 542, 705,  67, 371,  46, 526, 167,
       659,  69,  24, 325, 472, 680, 688, 484, 429, 219, 210, 154, 565,
       682, 616, 557, 481, 246, 504, 255, 493, 288, 110,  32, 482,  29,
       232, 477, 115,  68, 525, 448, 711, 696, 260, 170, 175, 679,  81,
       122, 513, 264, 609, 417, 665, 552, 364, 601, 615, 388, 348, 289,
       406,  41,  75, 386, 567,  97, 656, 540, 127,  20, 476, 107, 426,
       498, 704, 667, 359, 703, 155, 629,  51,   9, 131,  93,  12, 124,
       530, 261, 478, 338, 349,  71, 305, 631, 101, 277, 341,  82, 447,
       423, 226, 306, 398, 603,  43, 410, 333, 161, 529, 344, 158, 430,
        47, 453, 412, 291,  77, 138, 630, 624, 418, 569, 652, 147, 677,
       519,  42, 639, 307, 546, 516, 532, 276,  90, 651, 446, 474,  33,
       413, 553,   2, 212, 500, 709, 206, 621, 708, 468, 340, 166,  65,
        89, 409, 286, 455, 293,  17,  70, 367,  16, 528,   3, 241, 313,
       576, 390, 319, 309, 486, 377, 463, 690, 619, 197, 188, 610, 121,
       702, 494,  60, 266, 326, 520, 275, 671, 524, 111, 180,  92, 475,
       236, 159, 586, 240, 105, 614, 172, 201, 495, 221,  37, 668, 100,
       245, 608, 710,  64,  40,   5, 678,  48, 297, 694,  74, 562, 510,
       392, 693,  84, 285,  85, 470, 647, 336, 193, 269, 112, 402, 135,
       352, 284, 479, 583, 360, 499, 443, 508, 654, 488,   6, 372, 287,
       502, 249, 692, 559,  87, 454, 632, 211, 593, 438, 662, 146, 706,
       186, 568, 152, 538, 539,  91, 422, 374, 595, 134, 231, 560, 239,
       389, 310, 292, 535, 551, 202, 445, 588,  55, 537, 685, 235, 262,
       351, 451, 649,  21, 465, 254, 452, 267, 613,  54, 118, 686, 358,
       627, 548, 102, 379, 328, 268, 573, 658,  88, 342, 383, 618, 171,
       698, 459,  39, 623, 225,  18, 636, 123, 125, 391, 431, 527, 545,
       497, 393, 183, 441, 572, 157, 676, 405,  35, 523, 531, 674, 327,
       227, 561, 581, 329, 544, 220, 117, 308, 114, 399, 243, 177,  26,
        27,  72, 207, 483,  73, 265, 191, 643, 589, 401, 496, 699, 213,
       640, 707, 600, 489, 192, 626, 512, 370, 303,  36, 230, 575, 522,
       251, 596, 373, 150, 644, 209, 570, 638, 353, 244, 257, 563, 625,
       222, 145, 663, 365, 214, 350, 650, 337, 414, 378, 187, 396, 592,
        30, 104, 320, 185, 419,  76, 253, 700, 384, 471, 296,  99, 634,
       387, 421,  95,  66, 425, 620, 606, 194, 403, 162, 518, 355, 579,
       607,  53, 300, 169, 597, 622, 203, 375, 316, 323,  98, 217, 480,
       242,  57, 160, 156, 415, 324, 113, 168, 108, 190, 457, 695, 216,
       585, 657, 273, 128, 311, 501, 272, 106, 395, 517, 182, 229, 428,
       199, 380, 578, 681, 144, 381, 642, 343,  45, 594,  63, 250, 295,
       464, 382, 119, 153, 439, 641, 397, 278, 617, 224, 655, 366, 299,
       357, 259, 331, 142, 503, 549, 109, 347,  14, 312,  83, 653, 697,
       234, 408, 139, 577, 444, 628, 176,   1, 598, 437, 165, 683, 461,
       666, 369, 321, 290, 129,  58, 645, 571, 487,  62, 137, 218, 332,
       434, 280, 411, 356, 427, 330, 467, 223, 564,  50, 200, 420,  13,
       298, 602, 555, 195, 281, 252, 189, 507, 400, 505, 345, 664, 541,
       163, 133, 646, 315, 362,  34, 536, 449, 143,  10, 407, 611,  23,
       648, 318, 433, 334, 605, 314, 424, 550, 462, 515, 432, 701, 558,
        49,  19, 164, 521, 148,  11, 466, 587, 404, 178,   0, 435, 302,
        22, 635,  96, 416, 136,   8, 691, 184,  56, 294, 256, 637, 258,
       116, 215, 566, 363,  59,  78, 130, 669,   4, 469, 282, 534, 543,
       591, 436, 181,  61, 633, 556, 460, 274,  80, 205])

In [ ]:
df['Sex'] = le_country.fit_transform(df['Sex'])
df['Sex'].unique()

<ipython-input-31-afb583198a78>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sex'] = le_country.fit_transform(df['Sex'])

array([1, 0])

In [ ]:
df['Embarked'] = le_country.fit_transform(df['Embarked'])
df['Embarked'].unique()

<ipython-input-32-dfeab2faa02f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Embarked'] = le_country.fit_transform(df['Embarked'])

array([2, 0, 1])

In [ ]:
df.sample()

     Pclass  Name  Sex   Age  Embarked  Survived
843       3   404    1  34.5         0         0

In [ ]:
df.head()

   Pclass  Name  Sex   Age  Embarked  Survived
0       3   103    1  22.0         2         0
1       1   179    0  38.0         0         1
2       3   317    0  26.0         2         1
3       1   247    0  35.0         2         1
4       3    15    1  35.0         2         0

In [ ]:
#defining input columns
X = df[['Pclass',	'Name','Sex','Age','Embarked']]
X

     Pclass  Name  Sex   Age  Embarked
0         3   103    1  22.0         2
1         1   179    0  38.0         0
2         3   317    0  26.0         2
3         1   247    0  35.0         2
4         3    15    1  35.0         2
..      ...   ...  ...   ...       ...
885       3   556    0  39.0         1
886       2   460    1  27.0         2
887       1   274    0  19.0         2
889       1    80    1  26.0         0
890       3   205    1  32.0         1

[712 rows x 5 columns]

In [ ]:
y = df[['Survived']]
y

     Survived
0           0
1           1
2           1
3           1
4           0
..        ...
885         0
886         0
887         1
889         1
890         0

[712 rows x 1 columns]